// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: socketwithprotobuf.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum _em_server_message

typedef GPB_ENUM(_em_server_message) {
  _em_server_message_WsMsgServerLoginResp = 100,
  _em_server_message_WsMsgServerLoginNotify = 101,
  _em_server_message_WsMsgServerChatResp = 102,
  _em_server_message_WsMsgServerChatNotify = 103,
};

GPBEnumDescriptor *_em_server_message_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL _em_server_message_IsValidValue(int32_t value);

#pragma mark - Enum _em_client_message

typedef GPB_ENUM(_em_client_message) {
  _em_client_message_WsMsgClientLoginReq = 100,
  _em_client_message_WsMsgClientChatReq = 101,
};

GPBEnumDescriptor *_em_client_message_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL _em_client_message_IsValidValue(int32_t value);

#pragma mark - Enum _en_error_type

typedef GPB_ENUM(_en_error_type) {
  _en_error_type_LoginSuccess = 200,
  _en_error_type_LoginFailedWrongPass = 201,
  _en_error_type_ChatSuccess = 202,
};

GPBEnumDescriptor *_en_error_type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL _en_error_type_IsValidValue(int32_t value);

#pragma mark - SocketwithprotobufRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SocketwithprotobufRoot : GPBRootObject
@end

#pragma mark - _msg_login_req

typedef GPB_ENUM(_msg_login_req_FieldNumber) {
  _msg_login_req_FieldNumber_UserId = 1,
  _msg_login_req_FieldNumber_UserPass = 2,
};

@interface _msg_login_req : GPBMessage

@property(nonatomic, readwrite) int32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userPass;
/** Test to see if @c userPass has been set. */
@property(nonatomic, readwrite) BOOL hasUserPass;

@end

#pragma mark - _msg_login_resp

typedef GPB_ENUM(_msg_login_resp_FieldNumber) {
  _msg_login_resp_FieldNumber_ErrorCode = 1,
};

@interface _msg_login_resp : GPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite) BOOL hasErrorCode;
@end

#pragma mark - _msg_login_notify

typedef GPB_ENUM(_msg_login_notify_FieldNumber) {
  _msg_login_notify_FieldNumber_UserId = 1,
};

@interface _msg_login_notify : GPBMessage

@property(nonatomic, readwrite) int32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@end

#pragma mark - _msg_chat_req

typedef GPB_ENUM(_msg_chat_req_FieldNumber) {
  _msg_chat_req_FieldNumber_UserId = 1,
  _msg_chat_req_FieldNumber_ChatContent = 2,
};

@interface _msg_chat_req : GPBMessage

@property(nonatomic, readwrite) int32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *chatContent;
/** Test to see if @c chatContent has been set. */
@property(nonatomic, readwrite) BOOL hasChatContent;

@end

#pragma mark - _msg_chat_resp

typedef GPB_ENUM(_msg_chat_resp_FieldNumber) {
  _msg_chat_resp_FieldNumber_ErrorCode = 1,
};

@interface _msg_chat_resp : GPBMessage

@property(nonatomic, readwrite) int32_t errorCode;

@property(nonatomic, readwrite) BOOL hasErrorCode;
@end

#pragma mark - _msg_chat_notify

typedef GPB_ENUM(_msg_chat_notify_FieldNumber) {
  _msg_chat_notify_FieldNumber_UserId = 1,
  _msg_chat_notify_FieldNumber_ChatContent = 2,
};

@interface _msg_chat_notify : GPBMessage

@property(nonatomic, readwrite) int32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *chatContent;
/** Test to see if @c chatContent has been set. */
@property(nonatomic, readwrite) BOOL hasChatContent;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
